// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Team6_API.DataAccessLayer;

namespace Team6_API.Migrations
{
    [DbContext(typeof(DataAccessLayerDB))]
    [Migration("20220725034156_team6")]
    partial class team6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Team6_API.Model.EmployeeDB", b =>
                {
                    b.Property<int>("Emp_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Emp_Dept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Emp_Doj")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emp_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Emp_LeaveBal")
                        .HasColumnType("int");

                    b.Property<string>("Emp_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Emp_Phone")
                        .HasColumnType("bigint");

                    b.Property<int>("Man_Id")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Emp_Id");

                    b.HasIndex("Man_Id");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("Team6_API.Model.LeaveDetailsDB", b =>
                {
                    b.Property<int>("Leave_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Applied_On")
                        .HasColumnType("datetime2");

                    b.Property<int>("Emp_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Leave_Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leave_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leave_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Man_Id")
                        .HasColumnType("int");

                    b.Property<string>("Manager_Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("No_OfDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Leave_Id");

                    b.HasIndex("Emp_Id");

                    b.HasIndex("Man_Id");

                    b.ToTable("leaveDetails");
                });

            modelBuilder.Entity("Team6_API.Model.ManagerDB", b =>
                {
                    b.Property<int>("Man_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Man_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Man_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Man_Phone")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Man_Id");

                    b.ToTable("managers");
                });

            modelBuilder.Entity("Team6_API.Model.EmployeeDB", b =>
                {
                    b.HasOne("Team6_API.Model.ManagerDB", "manager")
                        .WithMany()
                        .HasForeignKey("Man_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("manager");
                });

            modelBuilder.Entity("Team6_API.Model.LeaveDetailsDB", b =>
                {
                    b.HasOne("Team6_API.Model.EmployeeDB", "EmployeeDB")
                        .WithMany()
                        .HasForeignKey("Emp_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Team6_API.Model.ManagerDB", "manager")
                        .WithMany()
                        .HasForeignKey("Man_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeDB");

                    b.Navigation("manager");
                });
#pragma warning restore 612, 618
        }
    }
}
